/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as AnunciarRouteImport } from './routes/anunciar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VeiculosSlugRouteImport } from './routes/veiculos.$slug'

const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnunciarRoute = AnunciarRouteImport.update({
  id: '/anunciar',
  path: '/anunciar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosSlugRoute = VeiculosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VeiculosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/comparar': typeof CompararRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/veiculos/$slug': typeof VeiculosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/comparar': typeof CompararRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/veiculos/$slug': typeof VeiculosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anunciar': typeof AnunciarRoute
  '/comparar': typeof CompararRoute
  '/dashboard': typeof DashboardRoute
  '/favoritos': typeof FavoritosRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/veiculos/$slug': typeof VeiculosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anunciar'
    | '/comparar'
    | '/dashboard'
    | '/favoritos'
    | '/veiculos'
    | '/veiculos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/anunciar'
    | '/comparar'
    | '/dashboard'
    | '/favoritos'
    | '/veiculos'
    | '/veiculos/$slug'
  id:
    | '__root__'
    | '/'
    | '/anunciar'
    | '/comparar'
    | '/dashboard'
    | '/favoritos'
    | '/veiculos'
    | '/veiculos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnunciarRoute: typeof AnunciarRoute
  CompararRoute: typeof CompararRoute
  DashboardRoute: typeof DashboardRoute
  FavoritosRoute: typeof FavoritosRoute
  VeiculosRoute: typeof VeiculosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anunciar': {
      id: '/anunciar'
      path: '/anunciar'
      fullPath: '/anunciar'
      preLoaderRoute: typeof AnunciarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/$slug': {
      id: '/veiculos/$slug'
      path: '/$slug'
      fullPath: '/veiculos/$slug'
      preLoaderRoute: typeof VeiculosSlugRouteImport
      parentRoute: typeof VeiculosRoute
    }
  }
}

interface VeiculosRouteChildren {
  VeiculosSlugRoute: typeof VeiculosSlugRoute
}

const VeiculosRouteChildren: VeiculosRouteChildren = {
  VeiculosSlugRoute: VeiculosSlugRoute,
}

const VeiculosRouteWithChildren = VeiculosRoute._addFileChildren(
  VeiculosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnunciarRoute: AnunciarRoute,
  CompararRoute: CompararRoute,
  DashboardRoute: DashboardRoute,
  FavoritosRoute: FavoritosRoute,
  VeiculosRoute: VeiculosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
