/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VeiculosRouteImport } from './routes/veiculos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VeiculosSlugRouteImport } from './routes/veiculos.$slug'

const VeiculosRoute = VeiculosRouteImport.update({
  id: '/veiculos',
  path: '/veiculos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VeiculosSlugRoute = VeiculosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => VeiculosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/veiculos/$slug': typeof VeiculosSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/veiculos/$slug': typeof VeiculosSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/veiculos': typeof VeiculosRouteWithChildren
  '/veiculos/$slug': typeof VeiculosSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/veiculos' | '/veiculos/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/veiculos' | '/veiculos/$slug'
  id: '__root__' | '/' | '/veiculos' | '/veiculos/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VeiculosRoute: typeof VeiculosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veiculos': {
      id: '/veiculos'
      path: '/veiculos'
      fullPath: '/veiculos'
      preLoaderRoute: typeof VeiculosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/veiculos/$slug': {
      id: '/veiculos/$slug'
      path: '/$slug'
      fullPath: '/veiculos/$slug'
      preLoaderRoute: typeof VeiculosSlugRouteImport
      parentRoute: typeof VeiculosRoute
    }
  }
}

interface VeiculosRouteChildren {
  VeiculosSlugRoute: typeof VeiculosSlugRoute
}

const VeiculosRouteChildren: VeiculosRouteChildren = {
  VeiculosSlugRoute: VeiculosSlugRoute,
}

const VeiculosRouteWithChildren = VeiculosRoute._addFileChildren(
  VeiculosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VeiculosRoute: VeiculosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
